### ISSUE TITLE
Error in modelTest

### ISSUE THREAD

**Issue by BH-Lab** [BPerezLamarque/HOME#2]
Dear Prof. Perez-Lamarque,
Thank you very much for providing this function.
When I ran Simulation and Empirical application using the same codes as introduced in HOME Tutorial and showed in Examples of this function, the function sim_microbiota ran normally, but the function HOME_model always ended with an Error:

Error in modelTest(sequences_model, model = c("K80", "F81", "HKY"), G = F, :
    Labels in tree and data differ!

I checked the lables in tree file and alignments, but they are the same. How could I to address this issue ?

**Comment by BPerezLamarque** [comment]
Hello,

This issue have been answered here (https://github.com/hmorlon/PANDA/issues/42). The problem came from the phangorn package that needed to be updated/reinstalled.

I am now closing this issue here also. 

All best, 
Benoît
